config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resources :books do
    get :return
    get :renew
    post :activate, on: :member
    post :deactivate, on: :member
  end

  resources :book_requests do
    post :fulfill, on: :member
  end

  namespace :students do
    get :dashboard, to: 'dashboard#show'
    get 'books/:id/borrow', to: 'books#borrow', as: :borrow_book
    get 'books/:id/pay', to: 'fines#pay', as: :pay_fine
  end

  namespace :staff do
    get :dashboard, to: 'dashboard#show'
    get 'books/:id/borrow', to: 'books#borrow', as: :borrow_book
    get 'books/:id/pay', to: 'fines#pay', as: :pay_fine
  end

  namespace :library_managers do
    get :dashboard, to: 'dashboard#show'
  end

  root to: 'static#index'
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :loans
  has_one_attached :cover_image
  has_one_attached :content

  validates_presence_of :title, :author, :reference_number, :book_type, :max_copies
  validates :cover_image, attached: true
  validates :cover_image, content_type: /\Aimage\/.*\z/
  validates :content, attached: true, content_type: { in: 'application/pdf', message: 'is not a PDF' }

  enum book_type: %i[book journal research_paper article]

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  def copies_available
    self.max_copies - Loan.on_loan.where(book: self).count
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy return activate deactivate]
  before_action :set_loan, only: %i[show return]
  before_action :require_library_manager, only: %i[new create edit update destroy activate deactivate]

  layout 'shared'

  # GET /books
  # GET /books.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: BookDatatable.new(params, view_context: view_context) }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    # Files are not auto-attached
    @book.cover_image.attach(params[:book][:cover_image])
    @book.content.attach(params[:book][:content])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    @book.cover_image.attach(params[:cover_image]) unless params[:cover_image].nil?
    @book.content.attach(params[:content]) unless params[:content].nil?

    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def return
    if @loan.update(returned_at: Time.now)
      redirect_to @book, notice: 'Book was successfully returned.'
    else
      redirect_to @book, alert: 'Could not return book.'
    end
  end

  def renew
    @book = Book.find(params['book_id'])
    @loan = Loan.find_by(book: @book, user: current_user, returned_at: nil)

    if @loan.to_be_returned_at < Time.now
      redirect_to @book, alert: 'Book is overdue. Please check your account for late return fees.' and return
    elsif @book.max_renewal.nil?
      redirect_to @book, alert: 'This book cannot be renewed.' and return
    elsif @loan.renewal_no == @book.max_renewal
      redirect_to @book, alert: 'Failed to renew book. You have reached the renewal limit.' and return
    else
      if @loan.update(renewed_at: Time.now, renewal_no: @loan.renewal_no + 1)
        redirect_to @book, notice: 'Book was successfully renewed.'
      else
        redirect_to @book, alert: 'Failed to renew book.'
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def activate
    respond_to do |format|
      if @book.update(active: true)
        format.html { redirect_to @book, notice: 'Book was successfully activated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { redirect_to @book, notice: 'Could not activate book.' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def deactivate
    respond_to do |format|
      if @book.update(active: false)
        format.html { redirect_to @book, notice: 'Book was successfully deactivated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { redirect_to @book, notice: 'Could not deactivate book.' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_book
    @book = Book.find(params[:id] || params['book_id'])
  end

  def set_loan
    @loan = Loan.on_loan.find_by(book: @book, user: current_user)

    redirect_to @book, alert: 'Loan not found' && return if @loan.blank?
  end

  def book_params
    params.require(:book).permit(
      :id, :cover_image, :content, :title, :author, :reference_number,
      :edition, :book_type, :description, :max_copies, :max_renewal
    )
  end
end

app/controllers/staff/books_controller.rb
class Staff::BooksController < Staff::StaffController
  before_action :set_book
  before_action :ensure_under_borrow_limit
  before_action :ensure_no_fines

  def borrow
    loan = Loan.new(book: @book, user: current_user, borrowed_at: Time.now)

    respond_to do |format|
      if loan.save
        format.html { redirect_to book_path(@book), notice: 'Book was borrowed successfully.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def ensure_under_borrow_limit
    return unless current_user.loans.on_loan.count == User::BORROW_LIMIT

    redirect_to(
      @book,
      alert: "You cannot borrow this book as you have hit the #{User::BORROW_LIMIT} book borrow limit"
    ) and return
  end

  def ensure_no_fines
    return unless current_user.has_overdue_loans?

    redirect_to @book, alert: 'You cannot borrow this book as you have an outstanding fine.' and return
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :reference_number, :edition, :active, :book_type, :author)
  end
end

app/controllers/students/books_controller.rb
class Students::BooksController < Students::StudentsController
  before_action :set_book
  before_action :ensure_under_borrow_limit
  before_action :ensure_no_fines

  def borrow
    loan = Loan.new(book: @book, user: current_user, borrowed_at: Time.now)

    respond_to do |format|
      if loan.save
        format.html { redirect_to book_path(@book), notice: 'Book was borrowed successfully.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  def ensure_under_borrow_limit
    return unless current_user.loans.on_loan.count == User::BORROW_LIMIT

    redirect_to(
      @book,
      alert: "You cannot borrow this book as you have hit the #{User::BORROW_LIMIT} book borrow limit"
    ) and return
  end

  def ensure_no_fines
    return unless current_user.has_overdue_loans?

    redirect_to @book, alert: 'You cannot borrow this book as you have an outstanding fine.' and return
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :reference_number, :edition, :active, :book_type, :author)
  end
end

app/views/books/_form.haml
:sass
  .question
    padding: 5px 10px

= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      %h2= "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      %ul
        - @book.errors.full_messages.each do |message|
          %li= message

  .question
    = f.label 'image', 'Cover Image:'
    = f.file_field :cover_image

  .question
    = f.label 'content', 'eBook PDF:'
    = f.file_field :content

  .question
    = f.label 'title', 'Title:'
    = f.text_field :title

  .question
    = f.label 'author', 'Author:'
    = f.text_field :author

  .question
    = f.label 'edition', 'Edition:'
    = f.number_field :edition, value: 1 , min: 1

  .question
    = f.label 'desc', 'Description:'
    %br
    = f.text_area :description, cols: 35, rows: 3

  .question
    = f.label 'reference_number', 'Reference Number:'
    = f.text_field :reference_number

  .question
    = f.label 'type', 'Type:'
    = f.select :book_type, :collection => Book.book_types.keys.to_a

  .question
    = f.label 'max_copies', 'Amount:'
    = f.number_field :max_copies, value: 1, min: 1

  .question
    = f.label 'max_renewal', 'Renewal limit:'
    = f.number_field :max_renewal, value: 4, min: 1

  .actions
    = link_to 'Back', books_path, class: 'btn btn-info'
    = f.submit 'Save', class: 'btn btn-success'

app/views/books/_form.html.haml
= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      %h2= "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      %ul
        - @book.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/books/edit.haml
%h1 Editing book

= render 'form'

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Show', @book
\|
= link_to 'Back', books_path

app/views/books/index.haml
:coffeescript
  $ ->
    $('#books_list').dataTable
      processing: true
      serverSide: true
      ajax:
        url: "/books"
      pagingType: 'full_numbers'
      columns: [
        { data: 'cover_image' }
        { data: 'title' }
        { data: 'author' }
        { data: 'book_type' }
        { data: 'reference_number' }
        { data: 'edition' }
        { data: 'copies_available' }
        { data: 'active' }
        { data: 'show' }
      ]

:sass
  #books_list tr
    text-align: center;
    vertical-align: middle;

%h3 Listing books

%table.table.table-hover#books_list
  %thead
    %tr
      %th
      %th Title
      %th Author
      %th Type
      %th Reference number
      %th Edition
      %th Copies available
      %th Active
      %th

- if current_user.library_manager?
  = link_to 'New Book', new_book_path, class: 'btn btn-button btn-success'

app/views/books/index.html.haml
%h1 Listing books

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @books.each do |book|
      %tr
        %td= link_to 'Show', book
        %td= link_to 'Edit', edit_book_path(book)
        %td= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Book', new_book_path

app/views/books/new.haml
%h1 Add Book

= render 'form'

app/views/books/new.html.haml
%h1 New book

= render 'form'

= link_to 'Back', books_path

app/views/books/show.haml
%h3 About this book

%b #{@book.title}
%p By #{@book.author}

- if @book.cover_image.attached?
  = image_tag @book.cover_image, height: '200px'
- else
  %p No image

%br
%br
%h3 Details
- if @book.description.present?
  %p Description: #{@book.description}
%p Book type: #{@book.book_type.gsub('_',' ').capitalize}
%p Active: #{@book.active == true ? 'Yes' : 'No' }
%p Reference Number: #{@book.reference_number}
%p Edition: #{@book.edition}
%p Copies Available: #{@book.copies_available}

- if @loan.present?
  %h2 About your loan
  %p Borrowed at: #{@loan.borrowed_at.strftime("%d/%m/%Y %T")}
  - if @loan.renewed_at != nil
    %p Renewed at: #{@loan.renewed_at.strftime("%d/%m/%Y %T")}
  %p Returned at: #{@loan.returned_at}
  %p To be returned at: #{@loan.to_be_returned_at.strftime("%d/%m/%Y %T")}
  - if @book.content.attached?
    = link_to 'Read', url_for(@book.content), target: '_blank', class: 'btn btn-info'

  - if @loan.overdue?
    %p This loan is overdue, you must pay $#{@loan.amount_pending} AUD
    - if current_user.student?
      = link_to 'Pay fine', students_pay_fine_path(@book), class: 'btn btn-danger'
    - elsif current_user.staff?
      = link_to 'Pay fine', staff_pay_fine_path(@book), class: 'btn btn-danger'
  - else
    = link_to 'Return book', book_return_path(@book), class: 'btn btn-primary'
    - if @loan.to_be_returned_at >= Time.now && @book.max_renewal.present?
      = link_to 'Renew book', book_renew_path(@book), class: 'btn btn-primary'

- else
  - if current_user.has_overdue_loans?
    %p You cannot borrow this book as you have an overdue loan which needs to be returned.
  - else
    - if current_user.student?
      = link_to 'Borrow book', students_borrow_book_path(@book), class: 'btn btn-success'
    - elsif current_user.staff?
      = link_to 'Borrow book', staff_borrow_book_path(@book), class: 'btn btn-success'

%br

- if current_user.library_manager?
  - if @book.loans.present?
    %h2 Loan History
    %table.table.table-hover
      %thead
        %tr 
          %th Borrower
          %th Borrow date
          %th Return date
          %th Late return
          %th Fine
      %tbody
      - @book.loans.each do |loan| 
        %tr
          %td= loan.user.first_name
          %td= loan.borrowed_at.strftime("%d/%m/%Y")
          - if loan.returned_at.nil?
            - if loan.overdue?
              - if loan.has_fine?
                %td Overdue loan, fine charged
                %td Yes
                %td Amount: $#{loan.amount_pending} - Unpaid
              - else
                %td Overdue loan 
                %td Yes
                %td Book to be returned before #{(loan.to_be_returned_at + 1.week).strftime("%d/%m/%Y")} to avoid fine.
            - else 
              %td Book still borrowed, due #{loan.to_be_returned_at.strftime("%d/%m/%Y")}
              %td N/A
              %td N/A
          - else 
            %td= loan.returned_at.strftime("%d/%m/%Y")
            - if loan.fine.nil?
              %td No 
              %td No fine
            - else 
              %td Yes
              %td Amount: $#{loan.amount_pending} - Paid
  %br

= link_to 'Back', books_path, class: 'btn btn-info'
- if current_user.library_manager?
  = link_to 'Edit', edit_book_path(@book), class: 'btn btn-primary'
  
  - unless @book.active?
    = link_to 'Activate', activate_book_path(@book), class: 'btn btn-success', method: :post
  
  - if @book.active? && @book.loans.on_loan.count.zero?
    = link_to 'Deactivate', deactivate_book_path(@book), class: 'btn btn-danger', method: :post

app/views/books/show.html.haml
%p#notice= notice

%h3 #{@book.title}
%p By: #{@book.author}
%p Book type: #{@book.book_type}
%p Active: #{@book.active}
%p Reference Number: #{@book.reference_number}
%p Edition: #{@book.edition}

= link_to 'Edit', edit_book_path(@book)
\|
= link_to 'Back', books_path