config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resources :books do
    get :return
    get :renew
    post :activate, on: :member
    post :deactivate, on: :member
  end

  resources :book_requests do
    post :fulfill, on: :member
  end

  namespace :students do
    get :dashboard, to: 'dashboard#show'
    get 'books/:id/borrow', to: 'books#borrow', as: :borrow_book
    get 'books/:id/pay', to: 'fines#pay', as: :pay_fine
  end

  namespace :staff do
    get :dashboard, to: 'dashboard#show'
    get 'books/:id/borrow', to: 'books#borrow', as: :borrow_book
    get 'books/:id/pay', to: 'fines#pay', as: :pay_fine
  end

  namespace :library_managers do
    get :dashboard, to: 'dashboard#show'
  end

  root to: 'static#index'
end

app/models/book_request.rb
class BookRequest < ApplicationRecord
    belongs_to :user

    validates_presence_of :title, :user
end

app/controllers/book_requests_controller.rb
class BookRequestsController < ApplicationController
    before_action :ensure_not_student
    before_action :require_staff, only: %i[new create destroy]

    layout 'shared'

    def index
        @book_requests = BookRequest.all
    end

    def show
        @book_request = BookRequest.find(params[:id])
    end

    def new
        @book_request = BookRequest.new()
    end

    def create 
        @book_request = BookRequest.new(book_request_params)
        @book_request.user = current_user

        respond_to do |format|
            if @book_request.save
                format.html { redirect_to @book_request, notice: 'Book Request was successfully created.' }
                format.json { render :show, status: :created, location: @book_request }
            else
                format.html { redirect_to @book_request, notice: 'Unable to create book request' }
                format.json { render json: @book_request.errors, status: :unprocessable_entity }
            end
        end

    end

    def fulfill
        @book_request = BookRequest.find(params[:id])
        @book_request.fulfillment = true
        respond_to do |format|
            if @book_request.save
                format.html { redirect_to book_requests_path, notice: 'Book Request was successfully marked as fulfilled' }
                format.json { render :show, status: :created, location: @book_request }
            else
                format.html { redirect_to book_requests_path, notice: 'Unable to mark book request as fulfilled.' }
                format.json { render json: @book_request.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @book_request = BookRequest.find(params[:id])
        @book_request.destroy
        respond_to do |format|
            format.html { redirect_to book_requests_url, notice: 'Book Request was successfully destroyed.' }
            format.json { head :no_content }
        end
    end
    

    def book_request_params
        params.require(:book_request).permit(:id, :title, :author, :edition)
    end

    def ensure_not_student
        return unless current_user.student? 
        
        redirect_to root_path, notice: 'Sorry, you\'re not allowed to view the page you requested.'
    end

end

app/views/book_requests/_form.haml
= form_for @book_request do |f| 
    = f.label 'title', 'Title:'
    = f.text_field :title
    %br

    = f.label 'author', 'Author:'
    = f.text_field :author
    %br

    = f.label 'edition', 'Edition:'
    = f.number_field :edition, min: 1
    %br

    = f.submit 'Send'

app/views/book_requests/index.haml
%h3 Book Requests

%table.table.table-hover#book_requests
  %thead
    %tr
      %th Title
      %th Author
      %th Edition
      %th Fulfillment
      %th

  %tbody
    - @book_requests.each do |book_request|
      %tr
        %td= book_request.title
        %td= book_request.author
        %td= book_request.edition
        %td= book_request.fulfillment == true ? "Yes" : "No"
        %td= link_to 'Show', book_request

%br

- if current_user.library_manager?
  = link_to 'Back to dashboard', library_managers_dashboard_path, class: 'btn btn-info'
- elsif current_user.student?
  = link_to 'Back to dashboard', students_dashboard_path, class: 'btn btn-info'
- elsif current_user.staff?
  = link_to 'Back to dashboard', staff_dashboard_path, class: 'btn btn-info'
  = link_to 'New Book Request', new_book_request_path, class: 'btn btn-success'

app/views/book_requests/new.haml
%h2 Make book request

= render 'form'

app/views/book_requests/show.haml
%h1 About this book request
%i The following book has been requested to be added to the library catalogue.
%br
%br

%p Title: #{@book_request.title}
%p By: #{@book_request.author}
- if @book_request.edition?
    %p Edition: #{@book_request.edition}

- if @book_request.user.id != current_user.id
    %p Requested By: #{@book_request.user.first_name} #{@book_request.user.last_name}
- else
    %p Requested By You
%p Fullfilled: #{@book_request.fulfillment == true ? 'Yes': 'No' }
%br

%p= link_to 'Back', book_requests_path, class: 'btn btn-info'
- if @book_request.user == current_user && @book_request.fulfillment == false
    %p= link_to 'Delete book request', book_request_path(@book_request), method: :delete, class: 'btn btn-danger'
- if current_user.library_manager? && @book_request.fulfillment == false
    %p= link_to 'Fulfill', fulfill_book_request_path(@book_request), class: 'btn btn-success', method: :post