config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resources :books do
    get :return
    get :renew
    post :activate, on: :member
    post :deactivate, on: :member
  end

  resources :book_requests do
    post :fulfill, on: :member
  end

  namespace :students do
    get :dashboard, to: 'dashboard#show'
    get 'books/:id/borrow', to: 'books#borrow', as: :borrow_book
    get 'books/:id/pay', to: 'fines#pay', as: :pay_fine
  end

  namespace :staff do
    get :dashboard, to: 'dashboard#show'
    get 'books/:id/borrow', to: 'books#borrow', as: :borrow_book
    get 'books/:id/pay', to: 'fines#pay', as: :pay_fine
  end

  namespace :library_managers do
    get :dashboard, to: 'dashboard#show'
  end

  root to: 'static#index'
end

app/views/layouts/_favicons.haml
%meta{ name: 'application-name', content: 'E Library' }
-# Browser favicon
%link{ rel: 'icon', sizes: '16x16', type: 'image/png', href: image_path('logos/book-16x16.png') }
-# Taskbar shortcut
%link{ rel: 'icon', sizes: '32x32', type: 'image/png', href: image_path('logos/book-32x32.png') }

app/views/layouts/_navbar.haml
:coffee
  $ ->
    $('#company-name, #company-logo').on 'click', ->
      window.location.href = '/'

:sass
  .in-session-alert
    margin-left: 30vw

  #company-logo
    margin: 5px
    cursor: pointer

  #company-name
    margin-left: 10px
    cursor: pointer

%nav.navbar.navbar-expand-lg.navbar-light.bg-light.border-bottom
  = image_tag 'logos/book-32x32', id: 'company-logo'

  #company-name
    %b{ style: 'font-size: 30px;' } E-Library

  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.ml-auto.mt-2.mt-lg-0
      .dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true",
         "data-toggle" => "dropdown", href: "#", role: "button"}
          = current_user.first_name
        .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
          = link_to 'Profile', edit_user_registration_path, class: 'dropdown-item'
          = link_to 'Logout', destroy_user_session_path, class: 'dropdown-item', method: :delete

app/views/layouts/_sidebar.haml
:coffee
  $ ->
    found = false

    if window.location.pathname.indexOf('dashboard') >= 0
      $('#home-item').addClass('on-page')
      found = true

    if window.location.pathname.indexOf('books') >= 0
      $('#books-item').addClass('on-page')
      found = true

    if window.location.pathname.indexOf('transcripts') >= 0
      $('#transcript-item').addClass('on-page')
      found = true

    if !found then $('#home-item').addClass('on-page')

:sass
  .on-page
    font-weight: bold


#sidebar-wrapper.bg-light
  .list-group.list-group-flush
    = link_to 'Home', root_path, class: 'list-group-item list-group-item-action bg-light', id: 'home-item'
    = link_to 'Books', books_path, class: 'list-group-item list-group-item-action bg-light',
      id: 'books-item'
  - unless current_user.student?
    = link_to 'Book requests', book_requests_path, class: 'list-group-item list-group-item-action bg-light',
      id: 'book-requests-item'

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title E-Library
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = render partial: 'layouts/favicons'
  %body
    - if notice.present?
      %p.notice= notice
    - if alert.present?
      %p.alert= alert
    = yield

app/views/layouts/bootstrap-mailer.haml
!!! Strict
%html
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    = stylesheet_link_tag "application-mailer", media: "all"
  %body.bg-light
    #wrap
      = yield

app/views/layouts/library_manager.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title E-Library
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p.notice= notice
    %p.alert= alert
    %b Library Manager
    %br
    = link_to 'Book Requests', book_requests_path
    = yield
    
    = link_to 'Log out', destroy_user_session_path, method: :delete
    = link_to 'Change info', edit_user_registration_path
    = link_to 'Books management', books_path

app/views/layouts/shared.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title E-Library
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = render partial: 'layouts/favicons'
  %body
    .page#container
      .header.no-print#header
        - if user_signed_in?
          = render partial: 'layouts/navbar'
        - else
          = yield :header
      
      .d-flex#wrapper
        - if user_signed_in?
          = render partial: 'layouts/sidebar'
        .col-8.col-md-10#main_content
          - if notice.present?
            %p.notice= notice
          - if alert.present?
            %p.alert= alert
          = yield

app/views/layouts/staff.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title E-Library
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = render partial: 'layouts/favicons'
  %body
    .page#container
      .header.no-print#header
        - if user_signed_in?
          = render partial: 'layouts/navbar'
        - else
          = yield :header
      
      .d-flex#wrapper
        - if user_signed_in?
          = render partial: 'layouts/sidebar'
        .col-8.col-md-10#main_content
          - if notice.present?
            %p.notice= notice
          - if alert.present?
            %p.alert= alert
          = yield

app/views/layouts/student.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title E-Library
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = render partial: 'layouts/favicons'
  %body
    .page#container
      .header.no-print#header
        - if user_signed_in?
          = render partial: 'layouts/navbar'
        - else
          = yield :header
    
      .d-flex#wrapper
        - if user_signed_in?
          = render partial: 'layouts/sidebar'
        .col-8.col-md-10#main_content
          - if notice.present?
            %p.notice= notice
          - if alert.present?
            %p.alert= alert
          = yield